### ISSUE TITLE
Exception while running workitem

### ISSUE THREAD

**Issue by VigneshMohan-code** [adamenagy/QuickerAssemblerDA#2]
@adamenagy  {"The server returned the non-success status code 403 (Forbidden).\nMore error details:\n\"User=<ClientID> cannot access a resource owned by Owner=AdamNagy.\"."}

How to resolve this?

**Comment by adamenagy** [comment]
I added a new environment variable for FORGE_NICKNAME that you'll have to set. More info in the readme:
https://github.com/adamenagy/QuickerAssemblerDA#running
